apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap
  namespace: default
data:
  index.html: |
    <html>
    <h3>Welcome</h3>
    <br>
    <h3>Hi! This is a configmap Index file</h3>
    </html>
