apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
     app.kubernetes.io/name: nginx
  name: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:latest
          name: nginx
          ports:
          - containerPort: 80
          volumeMounts:
          - name: index-html
            mountPath: /usr/share/nginx/html/index.html
      volumes:
      - name: index-html
        configMap:
          name: index-html-configmap

