apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: nginx
spec:
  interval: 1m
  path: ""
  sourceRef:
    kind: GitRepository
    name: flux
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml